# 这个文件用于定义lstm的参数

# 文件路径和数据
root_path: '/home/rolovoid/Desktop/cs/developer/python/data/shieldmachine/knife'
data_path: 'temp1.xlsx'
check_points: './checkpoints'

# 选取特征
cols: ''
target: '磨损效率'

batch_size: 32
seq_len: 16
pred_len: 4
label_len: 4

c_in: 16
c_out: 16
h_size: 32

num_layers: 2 # 用一个两层的lstm作为基线

# 数据采集
num_workers: 5
shuffle: True

# 训练工具
train_epochs: 400
use_early_stopping: True
patience: 50 # 用于早停的参数
lradj: 'type3' # 学习率参数，可选固定学习率(type3)/自适应学习率(type2)/动态学习率(type1)
learning_rate: 0.001 # 初始化优化器的学习率, 会受动态学习率工具制约
loss: 'mse' # 损失函数

checkpoints: './checkpoints'
predict_path: './runs/LSTM' # tensorboard测试/预测时的数据log所在文件夹

# 训练设备
use_gpu: True
gpu: 0
use_amp: '' # cuda的多元精度优化,暂时用不到